### ISSUE TITLE
[mayaa-user:1087] 独自プロセッサーを使うとエラーが発生する場合がある

### ISSUE THREAD

**Issue by ko-suga** [seasarorg/mayaa#13]
下記のもので a.html -> b.html の順で実行すると `ClassCastException` が発生する。

sample.mld

```
    <processor name="formatDate" class="com.example.FormatDateProcessor">
        <property name="value" required="true" expectedClass="java.time.LocalDateTime"/>
        <property name="default" expectedClass="java.lang.String"/>
        <property name="pattern" expectedClass="java.lang.String"/>
    </processor>
```

a.mayaa

```
  <m:beforeRender><![CDATA[
    var value = "TEST";
  ]]></m:beforeRender>
 
  <m:echo m:id="item">
    <m:attribute name="value" value="${value}" />
  </m:echo>
```

b.mayaa

```
  <m:beforeRender><![CDATA[
    var value = java.time.LocalDateTime.now();
  ]]></m:beforeRender>
 
  <a:formatDate m:id="item" value="${value}" pattern="yyyy-MM-dd" />
```

例外

```
java.lang.ClassCastException: Cannot cast java.lang.String to java.time.LocalDateTime
        at java.lang.Class.cast(Class.java:3369)
        at com.example.FormatDateProcessor.format(FormatDateProcessor.java:45)
        at com.example.FormatDateProcessor.doStartProcess(FormatDateProcessor.java:33)
        at org.seasar.mayaa.impl.engine.RenderUtil.renderTemplateProcessor(RenderUtil.java:134)
        at org.seasar.mayaa.impl.engine.RenderUtil.renderProcessorTree(RenderUtil.java:265)
        at org.seasar.mayaa.impl.engine.TemplateImpl.doTemplateRender(TemplateImpl.java:202)
        at org.seasar.mayaa.impl.engine.PageImpl.renderTemplate(PageImpl.java:241)
        at org.seasar.mayaa.impl.engine.RenderUtil.renderPage(RenderUtil.java:349)
        at org.seasar.mayaa.impl.engine.PageImpl.doPageRender(PageImpl.java:189)
        at org.seasar.mayaa.impl.engine.EngineImpl.doPageService(EngineImpl.java:373)
        at org.seasar.mayaa.impl.engine.EngineImpl.doService(EngineImpl.java:481)
        at org.seasar.mayaa.impl.MayaaServlet.doService(MayaaServlet.java:107)
        at org.seasar.mayaa.impl.MayaaServlet.doGet(MayaaServlet.java:90)
 ```

**Comment by mitonize** [comment]
再現コードを作成したいが発生する現象が異なる。
Class.cast でなく commons-beanutils が使われている。発生パターンが異なるのか。
```
java.lang.IllegalArgumentException: Cannot invoke org.seasar.mayaa.regressions.issue13.FormatDateProcessor.setValue on bean class 'class org.seasar.mayaa.regressions.issue13.FormatDateProcessor' - argument type mismatch - had objects of type "java.lang.String" but expected signature "java.time.LocalDateTime"
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2235)
	at org.apache.commons.beanutils.PropertyUtilsBean.setSimpleProperty(PropertyUtilsBean.java:2151)
	at org.apache.commons.beanutils.PropertyUtilsBean.setNestedProperty(PropertyUtilsBean.java:1957)
	at org.apache.commons.beanutils.PropertyUtilsBean.setProperty(PropertyUtilsBean.java:2064)
	at org.apache.commons.beanutils.PropertyUtils.setProperty(PropertyUtils.java:858)
	at org.seasar.mayaa.impl.util.ObjectUtil.setProperty(ObjectUtil.java:297)
	at org.seasar.mayaa.impl.builder.library.ProcessorDefinitionImpl.settingProperty(ProcessorDefinitionImpl.java:127)
	at org.seasar.mayaa.impl.builder.library.ProcessorDefinitionImpl.settingPropertySet(ProcessorDefinitionImpl.java:172)
	at org.seasar.mayaa.impl.builder.library.ProcessorDefinitionImpl.createTemplateProcessor(ProcessorDefinitionImpl.java:212)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.createProcessor(TemplateBuilderImpl.java:391)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.resolveInjectedNode(TemplateBuilderImpl.java:410)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.walkParsedTree(TemplateBuilderImpl.java:565)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.walkParsedTree(TemplateBuilderImpl.java:569)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.walkParsedTree(TemplateBuilderImpl.java:569)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.doInjection(TemplateBuilderImpl.java:645)
	at org.seasar.mayaa.impl.builder.TemplateBuilderImpl.afterBuild(TemplateBuilderImpl.java:191)
	at org.seasar.mayaa.impl.builder.SpecificationBuilderImpl.build(SpecificationBuilderImpl.java:79)
	at org.seasar.mayaa.impl.engine.specification.SpecificationImpl.build(SpecificationImpl.java:154)
	at org.seasar.mayaa.impl.engine.TemplateImpl.build(TemplateImpl.java:225)
	at org.seasar.mayaa.impl.engine.EngineImpl.createSpecificationInstance(EngineImpl.java:546)
	at org.seasar.mayaa.impl.engine.EngineImpl.createTemplateInstance(EngineImpl.java:586)
	at org.seasar.mayaa.impl.engine.PageImpl.getTemplateFromFixedSuffix(PageImpl.java:148)
	at org.seasar.mayaa.impl.engine.PageImpl.getTemplate(PageImpl.java:162)
	at org.seasar.mayaa.impl.engine.RenderUtil.getTemplate(RenderUtil.java:299)
	at org.seasar.mayaa.impl.engine.RenderUtil.renderPage(RenderUtil.java:335)
	at org.seasar.mayaa.impl.engine.PageImpl.doPageRender(PageImpl.java:189)
	at org.seasar.mayaa.impl.engine.EngineImpl.doPageService(EngineImpl.java:373)
	at org.seasar.mayaa.impl.engine.EngineImpl.doService(EngineImpl.java:481)
      （中略）
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.commons.beanutils.PropertyUtilsBean.invokeMethod(PropertyUtilsBean.java:2170)
	... 54 more
```

**Comment by mitonize** [comment]
java.time.LocalDateTime に対するコンバータの定義がないことが原因のよう。
java.time.LocalDateTime の箇所を java.util.Date にすると例外は発生しない。

**Comment by mitonize** [comment]
再現しなかったのはテスト用の FormatDateProcessorの作り方の問題だった。
問題の発生する状況が判明した。

ビルド済みのSpecにて保持されている`ProcessorProperty`内の `TextCompiledScriptImpl` の `_expectedClass` が書きかわっているため。

再現コード [b7936cd](https://github.com/seasarorg/mayaa/commit/b7936cda31193d359ce171762c7c47aaabfa8dd5)

[a -> b -> a という順序で実行](https://github.com/seasarorg/mayaa/commit/b7936cda31193d359ce171762c7c47aaabfa8dd5#diff-b696b09900a3e90496cd60ed49d7cccc10168d0bf03dbd1b789d6667044684eeR101)すると 
```
22:19:21.342 [main] ERROR o.s.mayaa.impl.engine.EngineImpl - Exception while handling error, Cannot convert TEST to java.time.LocalDateTime in script=
value
org.seasar.mayaa.impl.cycle.script.rhino.OffsetLineRhinoException: Cannot convert TEST to java.time.LocalDateTime in script=
value
	at org.seasar.mayaa.impl.cycle.script.rhino.TextCompiledScriptImpl.execute(TextCompiledScriptImpl.java:210)
```
[b -> a -> b という順序で実行](https://github.com/seasarorg/mayaa/commit/b7936cda31193d359ce171762c7c47aaabfa8dd5#diff-b696b09900a3e90496cd60ed49d7cccc10168d0bf03dbd1b789d6667044684eeR121)すると
```
22:19:51.978 [main] ERROR o.s.mayaa.impl.engine.EngineImpl - Exception while handling error, argument type mismatch: java.lang.String
java.lang.IllegalArgumentException: argument type mismatch: java.lang.String
	at org.seasar.mayaa.regressions.issue13.FormatDateProcessor.format(FormatDateProcessor.java:62)
```

また `${value}` を使用しない c.mayaa を用意すると交えて実行しても例外発生しない。

**Comment by mitonize** [comment]
やはり `${value}` で同じ CompiledScript のインスタンスに対して異なる expectedClass をセットしていた。
ScriptUtil.compile で CompiledScript を取得後の setExpectedClass が該当箇所。

対応するには下記の２つが考えられるが、CompiledScript 自体は本来 ExpectedClassには関係なく
JSのキャッシュ効率を考えると、やはり1の方法が望ましい。

1. CompiledScript に対して expectedClass を関連づけないようにして、ProcessorPropertyインスタンス側にその情報を持たせる。
2. expectedClass の情報とともに ScriptCache に保持させ、一致しないようにする。

**Comment by mitonize** [comment]
a6e544e にて CompiledScript に対して expectedClass を関連づけないようにして、ProcessorPropertyインスタンス側にその情報を持たせるようにした。
LiteralScript は String を前提とするようにしている。

**Comment by mitonize** [comment]
本件由来かは判明していないが下記の影響が出ており、対応のため再オープン。

HTMLソース
```html
<!-- ${ var nine = 9; } -->
<span class="script${nine}" data-value="${ nine }">${ nine }</span>
<!-- ${ var ten = 9; ten++; ""} -->
<span class="script${ten}" data-value="${ ten }">${ ten }</span>
```

Mayaa生成後
```html
<!--  -->
<span class="script9" data-value="9">9</span>
<!--  -->
<span class="script10.0" data-value="10.0">10</span>
```

**Comment by mitonize** [comment]
#97 にて解消
